baseurl = "https://www.paragliding-stuff.com/"
title = "Paragliding stuff"
theme = "portfolio"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-127559969-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Cool products about paragliding. Most products are self-designed. The designs are original and something very special for people with this extraordinary hobby. Paragliding is a wonderful way to experience the freedom of the sky and the magic of nature. These feelings are reflected in our products."
  copyright = "&copy;2018 Paragliding Stuff"
  sidebarAbout = [
    "Paragliding is a wonderful way to experience the freedom of the sky and the magic of nature. These feelings are reflected in our products.",
    "We are a creative illustrator and a computer enthusiast.",
    "We live in Essen, Germany"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "shop@paragliding-stuff.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "article/"
  home = false

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  email         = "shop@paragliding-stuff.com"