baseurl = "https://www.paragliding-stuff.com/"
title = "Paragliding stuff"
theme = "portfolio"
languageCode = "de-de"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-127559969-1"
DefaultContentLanguage = "de"

[languages]
  [languages.en]
    title = "Paragliding Stuff"
    weight = 10
    contentDir = "content/en"    
    baseurl = "https://www.paragliding-stuff.com/"
    [languages.en.params]
      description = "<strong>Cool products about paragliding.</strong> Most products are self-designed. Something very special for people with this extraordinary hobby. Paragliding is a wonderful way to experience the freedom of the sky and the magic of nature. These feelings are reflected in our products."
      sidebarAbout = [
        "Paragliding is a wonderful way to experience the freedom of the sky and the magic of nature. These feelings are reflected in our products.",
        "We are a creative illustrator and a computer enthusiast.",
        "We live in Essen, Germany"
      ]
      # Nav links in the side bar
      [[languages.en.params.navlinks]]
      name = "Home"
      url = "product/"
      home = false

      [[languages.en.params.navlinks]]
      name = "About"
      url = "about/"

      [[languages.en.params.navlinks]]
      name = "Get in touch"
      url = "contact/"

  [languages.de]
    title = "Paragliding Stuff"
    weight = 2
    contentDir = "content/de"    
    baseurl = "https://www.paragliding-stuff.de/"
    [languages.de.params]
      description = "<strong>Coole Produkte zum Thema Gleitschirmfliegen.</strong> Die meisten Produkte sind von uns selbst gestaltet, speziell für Freunde dieses phantastischen Hobbies. Gleitschirmfliegen ist eine wunderbare Möglichkeit, die Freiheit des Himmels und die Magie der Natur zu erleben. Diese Gefühle spiegeln sich in unseren Produkten wider."
      sidebarAbout = [
        "Gleitschirmfliegen ist eine wunderbare Möglichkeit, die Freiheit des Himmels und die Magie der Natur zu erleben. Diese Gefühle spiegeln sich in unseren Produkten wider.",
        "Wir sind eine kreative Illustratorin und ein Computer Freak.",
        "Wir leben in Essen, Deutschland"
      ]
      # Nav links in the side bar
      [[languages.de.params.navlinks]]
      name = "Produkte"
      url = "product/"
      home = false

      [[languages.de.params.navlinks]]
      name = "Über uns"
      url = "about/"

      [[languages.de.params.navlinks]]
      name = "Kontakt"
      url = "contact/"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  copyright = "&copy;2018 Paragliding Stuff"
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "shop@paragliding-stuff.com"


  [params.social]
  email         = "shop@paragliding-stuff.com"

  [params.opengraph]
  image="https://rlv.zcache.com/paragliders_into_the_sky_iphone_8_7_case-r4080c87c27ae4736b5c52a14f83658c8_ex79i_1024.jpg?rlvnet=1&max_dim=325"
  